// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtzSlwL1V5CRgQdWVTbOFS6UkI2A7--Zw',
    appId: '1:435977069172:web:300c051fd3391de0c6a721',
    messagingSenderId: '435977069172',
    projectId: 'superblogger-e0bce',
    authDomain: 'superblogger-e0bce.firebaseapp.com',
    storageBucket: 'superblogger-e0bce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNldZcPm4th00E_kUOKRppbXJWWt4-HJM',
    appId: '1:435977069172:android:7c6297368d3a2eb8c6a721',
    messagingSenderId: '435977069172',
    projectId: 'superblogger-e0bce',
    storageBucket: 'superblogger-e0bce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBimFXZZvq1g0GLLuGoMpGTXJ3iZB5zo10',
    appId: '1:435977069172:ios:847e5b61c26779d7c6a721',
    messagingSenderId: '435977069172',
    projectId: 'superblogger-e0bce',
    storageBucket: 'superblogger-e0bce.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBimFXZZvq1g0GLLuGoMpGTXJ3iZB5zo10',
    appId: '1:435977069172:ios:847e5b61c26779d7c6a721',
    messagingSenderId: '435977069172',
    projectId: 'superblogger-e0bce',
    storageBucket: 'superblogger-e0bce.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtzSlwL1V5CRgQdWVTbOFS6UkI2A7--Zw',
    appId: '1:435977069172:web:2ca08dabab7f3b71c6a721',
    messagingSenderId: '435977069172',
    projectId: 'superblogger-e0bce',
    authDomain: 'superblogger-e0bce.firebaseapp.com',
    storageBucket: 'superblogger-e0bce.appspot.com',
  );
}
